# Generated by Django 6.0.1 on 2026-03-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_formula_producto_presentacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('imagen', models.URLField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imagen de información',
                'verbose_name_plural': 'Imágenes de información',
                'ordering': ['orden', '-updated_at'],
            },
        ),
    ]
