# Generated by Django 6.0.1 on 2026-04-07 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_imageninformacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos_por_pagina', models.PositiveSmallIntegerField(default=12, help_text='Cuántos productos se muestran por página en el catálogo público (4–48).', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(48)])),
                ('max_imagenes_home', models.PositiveSmallIntegerField(default=6, help_text='Máximo de imágenes informativas visibles en el Home (1–20).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('max_destacados_home', models.PositiveSmallIntegerField(default=8, help_text='Máximo de productos destacados visibles en la sección de Home (1–20).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-destacado', '-updated_at']},
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(db_index=True, default=False, help_text='Aparece en la sección de destacados del Home y primero en el catálogo.'),
        ),
    ]
