# Generated by Django 6.0.1 on 2026-04-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_historial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses_retencion_historial', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
            },
        ),
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historiales'},
        ),
    ]
